version: '3'

services:
  gormigrate:
    image: gormigrate
    depends_on:
      - postgresql
      - mysql
    environment:
      PGPASSWORD: postgres
      PG_CONN_STRING: host=postgresql user=postgres dbname=gormigrate_test port=5432 sslmode=disable

      MYSQL_CONN_STRING: root:mysql@tcp(mysql)/gormigrate_test?multiStatements=true


  postgresql:
    image: postgres:11.2
    environment:
      POSTGRES_DB: gormigrate_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: gormigrate_test
      MYSQL_ROOT_PASSWORD: mysql
